name: login_firebase_bloc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  equatable: ^2.0.3
  firebase_core: ^2.24.2
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_input
  formz: ^0.6.0
  google_fonts: ^4.0.0
  meta: ^1.7.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository

  firebase_auth: ^4.15.3

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  mockingjay: ^0.5.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

# flutter_intl: 
#   enabled: false

dependency_overrides:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1